pipeline {
  agent {
    kubernetes {
      cloud 'team-k8s'
      // yamlFile './KubernetesPod.yaml'
      yaml '''
        apiVersion: v1
        kind: Pod      
        metadata:
          name: jenkins-slave
          namespace: jenkins-slave
          labels:
            class: KubernetesDeclarativeAgentTest
        spec:
          imagePullSecretes:
          - name: regcred
          containers:
          - name: docker 
            image: docker:20.10.12
            command: 
            - cat 
            tty: true
            volumeMounts: 
            - mountPath: /var/run/docker.sock
              name: docker-volume
          volumes:
          - name: docker-volume 
            hostPath: 
              path: /var/run/docker.sock 
              type: ""  
        '''.stripIndent()      
    }
  }  
  parameters {
    choice(name: 'BUILD_MODE', choices:['PATCH','HOTFIX','IMAGE'], description: 'Select the mode you want to act')
  
    string(name: 'HYPERAUTH', defaultValue: 'hyperauth.org', description: 'hyperauth url for login')
    string(name: 'REALM', defaultValue: 'tmax', description: 'hyperauth realm info')
    string(name: 'CLIENTID', defaultValue: 'ck-integration-hypercloud5', description: 'hyperauth client id info')
    string(name: 'MC_MODE', defaultValue: 'true', description: 'Choice multi cluster mode')    
  }
  triggers {
    // ref https://plugins.jenkins.io/parameterized-scheduler/
    // trigger at 9:00 every Thursday 
    parameterizedCron('''
    0 9 * * 4 %BUILD_MODE=PATCH
    ''')
  }
  environment { 
    BRANCH = "hc-dev-v5.1"
    BUILD_MODE = "${params.BUILD_MODE}"
  
    DOCKER_REGISTRY="tmaxcloudck"
    PRODUCT = "hypercloud-console"
    MAJOR_VER="5"
    MINOR_VER="0"
    PATCH_VER="0"
    HOTFIX_VER="0"
    VER = "${MAJOR_VER}.${MINOR_VER}.${PATCH_VER}.${HOTFIX_VER}"

    KEYCLOAK = "${params.KEYCLOAK}"
    REALM = "${params.REALM}"
    CLIENTID = "${params.CLIENTID}"
    MC_MODE = "${params.MC_MODE}"

    GUIDE_URL = "https://github.com/tmax-cloud/install-console/blob/5.0/README.md"
    
    USER_TOKEN = "jinsoo-access-token"
    USER_NAME = "jinsoo-youn"
    USER_EMAIL = "jinsoo_youn@tmax.co.kr"
  }
  stages {
    // When using SCM, the checkout stage can be completely omitted 
    stage('Git') {
      steps {
        git branch: "${BRANCH}", credentialsId: "${USER_NAME}", url: 'https://github.com/tmax-cloud/console.git'
        sh """
        git branch
        git pull origin ${BRANCH}:${BRANCH}
        """
         script {
            PATCH_VER = sh(script: 'cat ./CHANGELOG/tag.txt | head -2 | tail -1 | cut --delimiter="." --fields=3', returnStdout: true).trim()
            HOTFIX_VER = sh(script: 'cat ./CHANGELOG/tag.txt | head -2 | tail -1 | cut --delimiter="." --fields=4', returnStdout: true).trim()
          if (BUILD_MODE == 'PATCH') {
            def number = (PATCH_VER as int) + 1
            PATCH_VER = number.toString()
            HOTFIX_VER = "0"
            VER = "${MAJOR_VER}.${MINOR_VER}.${PATCH_VER}.${HOTFIX_VER}"
          } else if (BUILD_MODE == 'HOTFIX') {
            def hotfix_number = (HOTFIX_VER as int) + 1
            HOTFIX_VER = hotfix_number.toString()
            VER = "${MAJOR_VER}.${MINOR_VER}.${PATCH_VER}.${HOTFIX_VER}"
          }
        }
          sh """
            git config --global user.name ${USER_NAME}
            git config --global user.email ${USER_EMAIL}
          """        
          sh """
          git tag ${VER}
          echo "Console Version History" > ./CHANGELOG/tag.txt
          git tag --list "5.0.*" --sort=-version:refname >> ./CHANGELOG/tag.txt
          """
      }
    }

    stage('Build') {
      steps{
        container('docker'){
          withCredentials([usernamePassword(
            credentialsId: 'tmaxcloudck',
            usernameVariable: 'DOCKER_USER',
            passwordVariable: 'DOCKER_PWD')]){
            sh "docker login -u ${DOCKER_USER} -p ${DOCKER_PWD}"
            sh "docker build -t ${DOCKER_REGISTRY}/${PRODUCT}:${VER} -f ./Dockerfile ."
            sh "docker push ${DOCKER_REGISTRY}/${PRODUCT}:${VER}"
          }          
        }
      }
    }

    stage('Changelog'){
      when {
        anyOf {
          environment name: 'BUILD_MODE', value: 'PATCH'
          environment name: 'BUILD_MODE', value: 'HOTFIX'
        }
      }
      steps {
        script {
          if (BUILD_MODE == 'PATCH') {
            def number = (PATCH_VER as int) -1
            PATCH_VER = number.toString()
            HOTFIX_VER = "0"
            PRE_VER = "${MAJOR_VER}.${MINOR_VER}.${PATCH_VER}.${HOTFIX_VER}"
          } else if (BUILD_MODE == 'HOTFIX') {
            def hotfix_number = (HOTFIX_VER as int) - 1
            HOTFIX_VER = hotfix_number.toString()
            PRE_VER = "${MAJOR_VER}.${MINOR_VER}.${PATCH_VER}.${HOTFIX_VER}"
          }
        }
          sh """
            git config --global user.name ${USER_NAME}
            git config --global user.email ${USER_EMAIL}
          """
          sh """
            echo '# hypercloud-console patch note' > ./CHANGELOG/CHANGELOG-${VER}.md
            echo '## hypercloud-console_[major].[minor].[patch].[hotfix]' >> ./CHANGELOG/CHANGELOG-${VER}.md
            echo 'Version: ${PRODUCT}_${VER}' >> ./CHANGELOG/CHANGELOG-${VER}.md
            TZ=Asia/Seoul date '+%F  %r' >> ./CHANGELOG/CHANGELOG-${VER}.md
            git log --grep=[patch] -F --all-match --no-merges --date-order --reverse \
            --date=format:'%Y-%m-%d' \
            --pretty=format:'- %s (%ad %cn) %n    Note: %b' \
            --simplify-merges ${PRE_VER}..${VER} \
            >> ./CHANGELOG/CHANGELOG-${VER}.md
            sed -i '/Note: \r/d' ./CHANGELOG/CHANGELOG-${VER}.md
            sed -i 's/\[patch\]//g' ./CHANGELOG/CHANGELOG-${VER}.md
          """
          sh """
            cp -r ./console-helm-chart/values_ck_temp.yaml ./console-helm-chart/values_ck.yaml
            sed -i "s/@@VER@@/${VER}/g" ./console-helm-chart/values_ck.yaml
            cp -r ./console-helm-chart/values_team_temp.yaml ./console-helm-chart/values_team.yaml
            sed -i "s/@@VER@@/${VER}/g" ./console-helm-chart/values_team.yaml
          """
      }
    }

    stage('Email'){
      when {
        anyOf {
          environment name: 'BUILD_MODE', value: 'PATCH'
          environment name: 'BUILD_MODE', value: 'HOTFIX'
        }
      }
      steps {
        withCredentials([string(credentialsId: "${USER_TOKEN}", variable: 'GITHUB_ACCESS_TOKEN')]) { 
          sh """
            git push https://${GITHUB_ACCESS_TOKEN}@github.com/tmax-cloud/console.git HEAD:${BRANCH} --tags
            git add -A
            git commit -m 'Added changelog and updated history'
            git push https://${GITHUB_ACCESS_TOKEN}@github.com/tmax-cloud/console.git HEAD:${BRANCH}
          """        
        }
        emailext (
          to: 'cqa1@tmax.co.kr, ck1@tmax.co.kr, ck2@tmax.co.kr',
          subject: "[${PRODUCT}] Release Update - ${PRODUCT}:${VER}", 
          attachmentsPattern: "**/CHANGELOG/CHANGELOG-${VER}.md",
          body: "안녕하세요. \n\n${PRODUCT} Release Update 입니다. \n\n [필독] 타 모듈과의 버전을 맞추기위해 기존 5.1에서 5.0으로 변경했습니다. (PATCH, HOTFIX 는 기존 번호 유지)" + 
          "\n\n변경사항 파일로 첨부합니다. \n\n감사합니다.\n\n" +
                "※ 이미지 : ${DOCKER_REGISTRY}/${PRODUCT}:${VER} \n\n※ 설치 가이드 : ${GUIDE_URL} ",
          mimeType: 'text/plain'  
        )
      }
    }

  }

  post {
    success {
      sh "echo SUCCESSFUL"
      emailext (
        to: "jinsoo_youn@tmax.co.kr",
        subject: "SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
        body:  """<p>SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
            <p>Check console output at &QUOT;<a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a>&QUOT;</p>""",
        mimeType: 'text/html',    
      )
    } 
    failure {
      sh "echo FAILED"
      emailext (
        to: "jinsoo_youn@tmax.co.kr",
        subject: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
        body: """<p>FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
          <p>Check console output at &QUOT;<a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a>&QUOT;</p>""",
        mimeType: 'text/html'
      )
    }
  }
}