http:
  routers:
    console:
      rule: PathPrefix(`/`, `/static/`, `/api/resources/`,`/api/console`)
      entryPoints:
        - websecure
      service: console
      priority: 10
      tls: {}
    kubernetes:
      rule: PathPrefix(`/api/kubernetes/`)
      entryPoints:
        - websecure
      middlewares:
        - kubernetes-stripprefix
      service: kubernetes
      priority: 50
      tls: {}
    hypercloud:
      rule: PathPrefix(`/api/hypercloud/`, `/api/multi-hypercloud/`,`/api/webhook/`)
      entryPoints:
        - websecure
      middlewares:
        - hypercloud-stripprefix
      service: hypercloud
      priority: 50
      tls: {}
    monitoring:
      rule: PathPrefix(`/api/prometheus/`)
      entryPoints:
        - websecure
      service: monitoring
      priority: 50
      tls: []
    kibana:
      rule: PathPrefix(`/`) && Host(`kibana.tmaxcloud.local`)
      entryPoints:
        - websecure
      middlewares:
        - kibana-stripprefix
        - kibana-header
      service: kibana
      priority: 80
      tls: {}

  services:
    console:
      loadBalancer:
        serversTransport: insecure
        servers:
          - url: "http://@@MY_IP@@:9000"
    kubernetes:
      loadBalancer:
        serversTransport: insecure
        servers:
          - url: "https://192.168.9.189:6443"
    hypercloud:
      loadBalancer:
        serversTransport: insecure
        servers:
          - url: "https://192.168.9.193:31881"
    monitoring:
      loadBalancer:
        serversTransport: insecure
        servers:
          - url: "https://console.tmaxcloud.org"
    kibana:
      loadBalancer:
#        passHostHeader: true
#        healthCheck:
#          path: /api/kibana/
#          iterval: "1s"
#          timeout: "1s"
#          scheme: https
        serversTransport: insecure
        servers:
          - url: "https://kibana.tmaxcloud.org"

  middlewares:
    kubernetes-stripprefix:
      stripPrefix:
        prefixes:
        - /api/kubernetes/
    hypercloud-stripprefix:
      stripPrefix:
        prefixes:
          - /api/hypercloud
          - /api/multi-hypercloud
          - /api/webhook
    monitoring-addprefix:
      addPrefix:
        prefix: /api/prometheus
    kibana-addprefix:
      addPrefix:
        prefix: /app/kibana
    kibana-stripprefix:
      stripPrefix:
        prefixes:
          - /api/kibana/
    kibana-header:
      headers:
        addVaryHeader: true
#        accessControlAllowHeaders: true
#        accessControlAllowOriginList:
#          - https://kibana.tmaxcloud.org
        customRequestHeaders:
          Host: "kibana.tmaxcloud.org"
#        customReponseHeaders:
#          Host: "kibana.tmaxcloud.local"
#        hostsProxyHeaders:
#          Host: "kibana.tmaxcloud.org"

  serversTransports:
    insecure:
      insecureSkipVerify: true
      disableHTTP2: true
      serverName: kibana.tmaxcloud.org
