apiVersion: v1
kind: Service
metadata:
  name: console
  namespace: console-system
spec:
  type: NodePort
  ports:
  - name: "https"
    port: 80
    targetPort: 6443
    nodePort: 31304
  selector:
    app: console   
    hypercloud: ui
