apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
  namespace: api-gateway-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      labels:
        app: console
    spec:
      containers:
        - name: console
          command:
            - /opt/bridge/bin/console
            - server
            - --public-dir=/opt/bridge/static
            - --listen=http://0.0.0.0:31303
            - --base-address=http://0.0.0.0:31303
            - --keycloak-realm=tmax
            - --keycloak-auth-url=https://hyperauth.192.168.9.141.nip.io//auth
            - --keycloak-client-id=hypercloud5
            - --mc-mode=true
          image: tmaxcloudck/hypercloud-console:5.0.36.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 31303
              protocol: TCP
              name: console
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      serviceAccountName: console
